/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'vegetarian' : IDL.Bool,
});
export const OrderRequest = IDL.Record({
  'customerName' : IDL.Text,
  'phone' : IDL.Text,
  'deliveryPickup' : IDL.Text,
  'itemsOrdered' : IDL.Text,
});
export const Reservation = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'specialRequests' : IDL.Text,
  'time' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'guests' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRequest)], ['query']),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getMenuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
  'makeReservation' : IDL.Func([IDL.Text, Reservation], [], []),
  'placeOrder' : IDL.Func([IDL.Text, OrderRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'vegetarian' : IDL.Bool,
  });
  const OrderRequest = IDL.Record({
    'customerName' : IDL.Text,
    'phone' : IDL.Text,
    'deliveryPickup' : IDL.Text,
    'itemsOrdered' : IDL.Text,
  });
  const Reservation = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'specialRequests' : IDL.Text,
    'time' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'guests' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRequest)], ['query']),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getMenuByCategory' : IDL.Func([IDL.Text], [IDL.Vec(MenuItem)], ['query']),
    'makeReservation' : IDL.Func([IDL.Text, Reservation], [], []),
    'placeOrder' : IDL.Func([IDL.Text, OrderRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };