/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : number,
  'vegetarian' : boolean,
}
export interface OrderRequest {
  'customerName' : string,
  'phone' : string,
  'deliveryPickup' : string,
  'itemsOrdered' : string,
}
export interface Reservation {
  'date' : string,
  'name' : string,
  'specialRequests' : string,
  'time' : string,
  'email' : string,
  'phone' : string,
  'guests' : bigint,
}
export interface _SERVICE {
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrders' : ActorMethod<[], Array<OrderRequest>>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getMenuByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'makeReservation' : ActorMethod<[string, Reservation], undefined>,
  'placeOrder' : ActorMethod<[string, OrderRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];